---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: lines
  namespace: lines
spec:
  virtualhost:
    fqdn: lines.octetz.com
  routes:
    - match: /
      services:
        - name: lines
          port: 8000

---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: mountains
  namespace: lines
spec:
  virtualhost:
    fqdn: mountains.octetz.com
  routes:
    - match: /
      services:
        - name: lines
          port: 8000