---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: lines
  namespace: lines
spec:
  routes:
    - match: /dmv/line1
      services:
        - name: lines
          port: 8000