#!/bin/bash

CONTOUR_POD=$(kubectl -n contour get pod -l app=contour -o jsonpath='{.items[0].metadata.name}')
kubectl -n contour port-forward $CONTOUR_POD 6060 &>>/dev/null &
sleep .3
curl --silent localhost:6060/debug/dag | dot -T png > contour-dag.png
pkill kubectl

echo "DOT CREATED"
