---
apiVersion: v1
kind: Namespace
metadata:
  name: ping

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ping
  name: ping
  namespace: ping
spec:
  selector:
    matchLabels:
      app: ping
  replicas: 1 
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - image: joshrosso/ping:v1
        imagePullPolicy: IfNotPresent
        name: ping
        command: ["serve"]
        ports:
        - containerPort: 8000
          name: http

---
apiVersion: v1
kind: Service
metadata:
 name: pingv1
 namespace: ping
spec:
 type: ClusterIP
 ports:
 - port: 8000
   name: http
   protocol: TCP
   targetPort: 8000
 selector:
   app: ping