---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ping
  namespace: ping
spec:
  virtualhost:
    fqdn: ping.grego.corp.local
  routes:
    - services:
        - name: pingv1
          port: 8000
          weight: 10
        - name: pingv2
          port: 8000
          weight: 90
