apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: mountains
  namespace: mountains
spec:
  virtualhost:
    fqdn: mountains.octetz.com
    tls:
      secretName: octetz-tls
  routes:
    - match: /
      services:
        - name: mountains
          port: 8000